In [52]:
import pandas as pd

In [53]:
import urllib
%matplotlib inline

In [54]:
dir = '../resources/data/'

In [55]:
#download dataset from source https://github.com/planetsig/ufo-reports
url = 'https://github.com/planetsig/ufo-reports/raw/master/csv-data/ufo-scrubbed-geocoded-time-standardized.csv'
response = urllib.request.urlopen(url)
data = response.read()
with open(dir + 'ufo-complete-geocoded-time-standardized.csv', 'wb') as f:
    f.write(data)

In [56]:
#read data into dataframe
df = pd.read_csv(dir + 'ufo-complete-geocoded-time-standardized.csv', 
                 names = ['datetime', 'city', 'state', 'country', 'shape', 'duration (seconds)', 
                          'duration (hours/minutes)', 'comments', 'date posted', 'latitude', 'longitude'])

In [57]:
#convert duration (seconds) to float
df['duration (seconds)'] = pd.to_numeric(df['duration (seconds)'], errors='coerce')

#convert date posted to datetime
df['date posted'] = pd.to_datetime(df['date posted'])

In [58]:
df.head(10)

,datetime,city,state,country,shape,duration (seconds),duration (hours/minutes),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700.0,45 minutes,This event took place in early fall around 194...,2004-04-27,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200.0,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,2005-12-16,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20.0,20 seconds,Green/Orange circular disc over Chester&#44 En...,2008-01-21,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20.0,1/2 hour,My older brother and twin sister were leaving ...,2004-01-17,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,2004-01-22,21.4180556,-157.803611
5,10/10/1961 19:00,bristol,tn,us,sphere,300.0,5 minutes,My father is now 89 my brother 52 the girl wit...,2007-04-27,36.5950000,-82.188889
6,10/10/1965 21:00,penarth (uk/wales),NaN,gb,circle,180.0,about 3 mins,penarth uk circle 3mins stayed 30ft above m...,2006-02-14,51.434722,-3.180000
7,10/10/1965 23:45,norwalk,ct,us,disk,1200.0,20 minutes,A bright orange color changing to reddish colo...,1999-10-02,41.1175000,-73.408333
8,10/10/1966 20:00,pell city,al,us,disk,180.0,3 minutes,Strobe Lighted disk shape object observed clos...,2009-03-19,33.5861111,-86.286111
9,10/10/1966 21:00,live oak,fl,us,disk,120.0,several minutes,Saucer zaps energy from powerline as my pregna...,2005-05-11,30.2947222,-82.984167

**Question 1** What is the most common 'shape' of a ufo seen?

In [59]:
df ['shape'].value_counts().head(1)

light    16565
Name: shape, dtype: int64

**Question 2** When was the first sighting? note: use the 'datetime' column

In [61]:
df.sort_values('datetime',ascending=True).head(1)

,datetime,city,state,country,shape,duration (seconds),duration (hours/minutes),comments,date posted,latitude,longitude
10580,1/1/1910 24:00,kirksville (near),mo,us,disk,120.0,minutes,Historical sighting (1903 - 1913) Northern Mis...,2005-09-15,40.1947222,-92.583056

**Question 3** What is the average length of a sighting?

In [ ]:
df['duration (seconds)'].mean()

**Question 4** How many sightings were over 3 minutes?

In [24]:
df[df['duration (seconds)'] >180].shape[0]

37685

**Question 5**: Of the sightings that were over 3 minutes, how many were in NJ?

In [25]:
df[(df['duration (seconds)'] >180 ) & (df['state'] == 'nj')].shape[0]

686

**Question 6**: What state has the most ufo sightings?

In [26]:
df['state'].value_counts().head(1)

ca    9655
Name: state, dtype: int64

**Question 7**: Can you change the column header 'shape' to be called 'ufo shape'? Note we did not go over this in class. You will need to look through the documentation (http://pandas.pydata.org/pandas-docs/stable/)

In [27]:
df.rename(columns={"shape":"ufo shape"})

,datetime,city,state,country,ufo shape,duration (seconds),duration (hours/minutes),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700.0,45 minutes,This event took place in early fall around 194...,2004-04-27,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200.0,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,2005-12-16,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20.0,20 seconds,Green/Orange circular disc over Chester&#44 En...,2008-01-21,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20.0,1/2 hour,My older brother and twin sister were leaving ...,2004-01-17,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,2004-01-22,21.4180556,-157.803611
5,10/10/1961 19:00,bristol,tn,us,sphere,300.0,5 minutes,My father is now 89 my brother 52 the girl wit...,2007-04-27,36.5950000,-82.188889
6,10/10/1965 21:00,penarth (uk/wales),NaN,gb,circle,180.0,about 3 mins,penarth uk circle 3mins stayed 30ft above m...,2006-02-14,51.434722,-3.180000
7,10/10/1965 23:45,norwalk,ct,us,disk,1200.0,20 minutes,A bright orange color changing to reddish colo...,1999-10-02,41.1175000,-73.408333
8,10/10/1966 20:00,pell city,al,us,disk,180.0,3 minutes,Strobe Lighted disk shape object observed clos...,2009-03-19,33.5861111,-86.286111
9,10/10/1966 21:00,live oak,fl,us,disk,120.0,several minutes,Saucer zaps energy from powerline as my pregna...,2005-05-11,30.2947222,-82.984167
10,10/10/1968 13:00,hawthorne,ca,us,circle,300.0,5 min.,ROUND &#44 ORANGE &#44 WITH WHAT I WOULD SAY W...,2003-10-31,33.9163889,-118.351667
11,10/10/1968 19:00,brevard,nc,us,fireball,180.0,3 minutes,silent red /orange mass of energy floated by t...,2008-06-12,35.2333333,-82.734444
12,10/10/1970 16:00,bellmore,ny,us,disk,1800.0,30 min.,silver disc seen by family and neighbors,2000-05-11,40.6686111,-73.527500
13,10/10/1970 19:00,manchester,ky,us,unknown,180.0,3 minutes,Slow moving&#44 silent craft accelerated at an...,2008-02-14,37.1536111,-83.761944
14,10/10/1971 21:00,lexington,nc,us,oval,30.0,30 seconds,green oval shaped light over my local church&#...,2010-02-14,35.8238889,-80.253611
15,10/10/1972 19:00,harlan county,ky,us,circle,1200.0,20minutes,On october 10&#44 1972 myself&#44my 5yrs.daugh...,2005-09-15,36.8430556,-83.321944
16,10/10/1972 22:30,west bloomfield,mi,us,disk,120.0,2 minutes,The UFO was so close&#44 my battery in the car...,2007-08-14,42.5377778,-83.233056
17,10/10/1973 19:00,niantic,ct,us,disk,1800.0,20-30 min,Oh&#44 what a night &#33 Two (2) saucer-shape...,2003-09-24,41.3252778,-72.193611
18,10/10/1973 23:00,bermuda nas,NaN,NaN,light,20.0,20 sec.,saw fast moving blip on the radar scope thin w...,2002-01-11,32.364167,-64.678611
19,10/10/1974 19:30,hudson,ma,us,other,2700.0,45 minutes,Not sure of the eact month or year of this sig...,1999-08-10,42.3916667,-71.566667
20,10/10/1974 21:30,cardiff (uk/wales),NaN,gb,disk,1200.0,20 minutes,back in 1974 I was 19 at the time and lived i...,2007-02-01,51.5,-3.200000
21,10/10/1974 23:00,hudson,ks,us,light,1200.0,one hour?,The light chased us.,2004-07-25,38.1055556,-98.659722
22,10/10/1975 17:00,north charleston,sc,us,light,360.0,5-6 minutes,Several Flashing UFO lights over Charleston Na...,2008-02-14,32.8544444,-79.975000
23,10/10/1976 20:30,washougal,wa,us,oval,60.0,1 minute,Three extremely large lights hanging above nea...,2014-02-07,45.5827778,-122.352222
24,10/10/1976 22:00,stoke mandeville (uk/england),NaN,gb,cigar,3.0,3 seconds,White object over Buckinghamshire UK.,2009-12-12,51.783333,-0.783333
25,10/10/1977 12:00,san antonio,tx,us,other,30.0,30 seconds,i was about six or seven and my family and me ...,2005-02-24,29.4238889,-98.493333
26,10/10/1977 22:00,louisville,ky,us,light,30.0,approx: 30 seconds,HBCCUFO CANADIAN REPORT: Pilot Sighting Of Un...,2004-03-17,38.2541667,-85.759444
27,10/10/1978 02:00,elmont,ny,us,rectangle,300.0,5min,A memory I will never forget that happened men...,2007-02-01,40.7008333,-73.713333
28,10/10/1979 00:00,poughkeepsie,ny,us,chevron,900.0,15 minutes,1/4 moon-like&#44 its &#39chord&#39 or flat s...,2005-04-16,41.7002778,-73.921389
29,10/10/1979 22:00,saddle lake (canada),ab,NaN,triangle,270.0,4.5 or more min.,Lights far above&#44 that glance; then flee f...,2005-01-19,53.970571,-111.689885
...,...,...,...,...,...,...,...,...,...,...,...
80302,9/9/2012 20:00,wilson,nc,us,light,10800.0,3 hours,Bright orb being chased by a jet along with se...,2012-09-24,35.7211,-77.915833
80303,9/9/2012 20:10,elmont,ny,us,circle,600.0,10 minutes,Orange lights seen in Elmont&#44 Long Island&#...,2012-09-24,40.7008,-73.713333
80304,9/9/2012 20:30,mt. juliet,tn,us,light,120.0,2 minutes,Bright white light moving slowly across sky wi...,2012-09-24,36.2,-86.518611
80305,9/9/2012 20:30,ventura,ca,us,chevron,900.0,15 minutes,Beautiful bright blue delta shaped aerobatics.,2012-09-24,34.2783,-119.292222
80306,9/9/2012 20:52,south jordan,ut,us,circle,10.0,10 seconds,Circular disk with blinking lights scares two ...,2012-09-24,40.5622,-111.928889
80307,9/9/2012 21:00,elkhart,in,us,oval,600.0,10 minutes,It was the night of sept 9 between 9 and 10 pm...,2012-09-24,41.6819,-85.976667
80308,9/9/2012 21:00,new york city (brooklyn),ny,us,light,1290.0,21:30,Glowing&#44 circular lights visible in the clo...,2012-09-24,40.7142,-74.006389
80309,9/9/2012 21:00,pawleys island,sc,us,oval,60.0,less than a minute,One large bright orange flanked by three small...,2012-09-24,33.4331,-79.121667
80310,9/9/2012 21:00,ventura,ca,us,circle,300.0,5 minutes,Bright Blue Object seen floating in sky near C...,2012-09-24,34.2783,-119.292222
80311,9/9/2012 21:55,charleston,sc,us,flash,900.0,15 minutes,Orb of light flashing reds and blues&#44 stati...,2012-09-24,32.7764,-79.931111
80312,9/9/2012 23:00,gainesville,ga,us,light,5.0,5 seconds,Ball of light,2012-09-24,34.2978,-83.824167
80313,9/9/2013 00:15,norfolk,va,us,unknown,1.0,split second,Two or three lights shoot across sky over nava...,2013-09-30,36.8467,-76.285556
80314,9/9/2013 01:50,buffalo (west of; on highway 90 west),ny,us,triangle,180.0,3 minutes,Massive Flat Black triangle with 3 red lights.,2013-09-30,42.8864,-78.878611
80315,9/9/2013 03:00,struthers,oh,us,unknown,120.0,2 minutes,I saw a routaing line of stares that seemed to...,2013-09-09,41.0525,-80.608056
80316,9/9/2013 09:51,san diego,ca,us,light,4.0,~4 seconds,2 white lights zig-zag over Qualcomm Stadium (...,2013-09-30,32.7153,-117.156389
80317,9/9/2013 12:34,cedar park,tx,us,cigar,8.0,5-8 seconds,Cigar Shaped Object Descending in the Directio...,2013-09-09,30.505,-97.820000
80318,9/9/2013 13:10,calmar (canada),ab,ca,unknown,90.0,45-90 seconds,Fastest dot I have ever seen in the sky&#33,2013-09-09,53.25,-113.783333
80319,9/9/2013 20:15,clifton,nj,NaN,other,3600.0,~1hr+,Luminous line seen in New Jersey sky.,2013-09-30,40.8584,-74.163755
80320,9/9/2013 20:20,tuscaloosa,al,us,fireball,60.0,1:00,White/green object much larger than &quot;shoo...,2013-09-30,33.2097,-87.569167
80321,9/9/2013 20:21,clarksville,tn,us,fireball,3.0,3 seconds,Green fireball like object shooting across the...,2013-09-30,36.5297,-87.359444
80322,9/9/2013 21:00,aleksandrow (poland),NaN,NaN,light,15.0,15 seconds,Two points of light following one another in a...,2013-09-30,50.4658,22.891814
80323,9/9/2013 21:00,gainesville,fl,us,triangle,60.0,1 minute,Three lights in the sky that didn&#39t look li...,2013-09-30,29.6514,-82.325000
80324,9/9/2013 21:00,hamstead (hollyridge),nc,NaN,light,120.0,2 minutes,8 to ten lights bright orange in color large t...,2013-09-30,34.3676,-77.710548
80325,9/9/2013 21:00,milton (canada),on,ca,fireball,180.0,3 minutes,Massive Bright Orange Fireball in Sky,2013-09-30,46.3,-63.216667
80326,9/9/2013 21:00,woodstock,ga,us,sphere,20.0,20 seconds,Driving 575 at 21:00 hrs saw a white and green...,2013-09-30,34.1014,-84.519444
80327,9/9/2013 21:15,nashville,tn,us,light,600.0,10 minutes,Round from the distance/slowly changing colors...,2013-09-30,36.1658,-86.784444
80328,9/9/2013 22:00,boise,id,us,circle,1200.0,20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...,2013-09-30,43.6136,-116.202500
80329,9/9/2013 22:00,napa,ca,us,other,1200.0,hour,Napa UFO&#44,2013-09-30,38.2972,-122.284444
80330,9/9/2013 22:20,vienna,va,us,circle,5.0,5 seconds,Saw a five gold lit cicular craft moving fastl...,2013-09-30,38.9011,-77.265556
80331,9/9/2013 23:00,edmond,ok,us,cigar,1020.0,17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...,2013-09-30,35.6528,-97.477778